version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
