version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
  server:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db-data:
